CREATE TABLE ROAD_ADDR_INTG
AS
SELECT DISTINCT J.MGR_NO, R.SIDO_NAME, R.SIGUNGU_NAME, R.ROAD_NAME, J.BLDG_MAIN_NO, J.BLDG_SUB_NO,  A.CONST_BLDG_NAME, A.POST_CODE
      ,CONCAT(R.SIDO_NAME,' ',R.SIGUNGU_NAME,' ',ROAD_NAME,' ',BLDG_MAIN_NO
             ,(CASE WHEN BLDG_SUB_NO != '0' THEN CONCAT('-',BLDG_SUB_NO) ELSE ''END),' '
             ,CONCAT('(',B.UMD_NAME,(CASE WHEN CONST_BLDG_NAME IS NOT NULL THEN CONCAT(',',CONST_BLDG_NAME) ELSE '' END),')')) AS FULL_ROAD_ADDR
  FROM ROAD_CODE R INNER JOIN JUSO J ON R.ROAD_ADDR_CODE = J.ROAD_ADDR_CODE
                   INNER JOIN ADD_INFO A  ON J.MGR_NO = A.MGR_NO
                   INNER JOIN JIBUN B ON J.MGR_NO = B.MGR_NO AND B.SEQ_NO = 1
;

CREATE TABLE JIBUN_ADDR_INTG
AS
SELECT A.*, CONCAT(SIDO_NAME,' ',SIGUNGU_NAME,' ',UMD_NAME,' ',(CASE WHEN SAN_YN = 1 THEN '산' ELSE '' END),JIBN_MAIN_NO,(CASE WHEN JIBN_SUB_NO != 0 THEN CONCAT('-',JIBN_SUB_NO) ELSE '' END)) AS FULL_JIBN_ADDR
FROM JIBUN A
;